import { Producto, Insumo } from '../types';

export const DEFAULT_INSUMOS: Insumo[] = [
  { id: 1, nombre: 'Harina de Trigo Especial W300', unidad_medida: 'kg', costo_unitario: 4200, stock_actual: 85, stock_minimo: 25, stock_inicial: 85 },
  { id: 2, nombre: 'Levadura Fresca Prensada', unidad_medida: 'kg', costo_unitario: 18000, stock_actual: 3.5, stock_minimo: 2, stock_inicial: 3.5 },
  { id: 3, nombre: 'Masa Madre Natural Activa', unidad_medida: 'kg', costo_unitario: 5000, stock_actual: 12, stock_minimo: 5, stock_inicial: 12 },
  { id: 4, nombre: 'Mantequilla Artesanal 82% MG', unidad_medida: 'kg', costo_unitario: 32000, stock_actual: 7.2, stock_minimo: 6, stock_inicial: 7.2 },
  { id: 5, nombre: 'Sal Marina Fina', unidad_medida: 'kg', costo_unitario: 2000, stock_actual: 18, stock_minimo: 5, stock_inicial: 18 },
  { id: 6, nombre: 'Azúcar Blanca Refinada', unidad_medida: 'kg', costo_unitario: 4600, stock_actual: 15, stock_minimo: 8, stock_inicial: 15 },
  { id: 7, nombre: 'Agua Purificada Filtrada', unidad_medida: 'L', costo_unitario: 200, stock_actual: 500, stock_minimo: 100, stock_inicial: 500 },
  { id: 8, nombre: 'Chocolate Repostería 65%', unidad_medida: 'kg', costo_unitario: 48000, stock_actual: 3.5, stock_minimo: 5, stock_inicial: 3.5 },
  { id: 9, nombre: 'Aceite de Oliva Virgen Extra', unidad_medida: 'L', costo_unitario: 36000, stock_actual: 4.5, stock_minimo: 3, stock_inicial: 4.5 },
  { id: 10, nombre: 'Queso Campesino Rallado', unidad_medida: 'kg', costo_unitario: 24000, stock_actual: 9, stock_minimo: 4, stock_inicial: 9 },
];

export const DEFAULT_PRODUCTOS: Producto[] = [
  {
    id: 1,
    nombre: 'Baguette Tradicional Francesa',
    descripcion: 'Corteza crujiente dorada y miga alveolada con 24h de fermentación lenta.',
    precio: 3500,
    categoria: 'Pan Rústico',
    imagen_url: '/images/pan_estrella_1.jpg',
    stock_disponible: 32,
    activo: 1,
    costo_produccion_unitario: 1402,
    receta: [
      { id: 1, producto_id: 1, insumo_id: 1, cantidad: 0.30, insumo_nombre: 'Harina de Trigo Especial W300', unidad_medida: 'kg', costo_unitario: 4200, subtotal_costo: 1260 },
      { id: 2, producto_id: 1, insumo_id: 2, cantidad: 0.005, insumo_nombre: 'Levadura Fresca Prensada', unidad_medida: 'kg', costo_unitario: 18000, subtotal_costo: 90 },
      { id: 3, producto_id: 1, insumo_id: 5, cantidad: 0.006, insumo_nombre: 'Sal Marina Fina', unidad_medida: 'kg', costo_unitario: 2000, subtotal_costo: 12 },
      { id: 4, producto_id: 1, insumo_id: 7, cantidad: 0.20, insumo_nombre: 'Agua Purificada Filtrada', unidad_medida: 'L', costo_unitario: 200, subtotal_costo: 40 },
    ],
  },
  {
    id: 2,
    nombre: 'Pan Campesino de Masa Madre',
    descripcion: 'Hogaza rústica 100% masa madre con greña pronunciada y acidez equilibrada.',
    precio: 15000,
    categoria: 'Especiales',
    imagen_url: '/images/pan_estrella_2.jpg',
    stock_disponible: 18,
    activo: 1,
    costo_produccion_unitario: 3160,
    receta: [
      { id: 5, producto_id: 2, insumo_id: 1, cantidad: 0.55, insumo_nombre: 'Harina de Trigo Especial W300', unidad_medida: 'kg', costo_unitario: 4200, subtotal_costo: 2310 },
      { id: 6, producto_id: 2, insumo_id: 3, cantidad: 0.15, insumo_nombre: 'Masa Madre Natural Activa', unidad_medida: 'kg', costo_unitario: 5000, subtotal_costo: 750 },
      { id: 7, producto_id: 2, insumo_id: 5, cantidad: 0.012, insumo_nombre: 'Sal Marina Fina', unidad_medida: 'kg', costo_unitario: 2000, subtotal_costo: 24 },
      { id: 8, producto_id: 2, insumo_id: 7, cantidad: 0.38, insumo_nombre: 'Agua Purificada Filtrada', unidad_medida: 'L', costo_unitario: 200, subtotal_costo: 76 },
    ],
  },
  {
    id: 3,
    nombre: 'Croissant Francés de Mantequilla',
    descripcion: 'Hojaldre artesanal con mantequilla pura al 82%, capas finas y esponjosas.',
    precio: 5500,
    categoria: 'Bollería / Dulce',
    imagen_url: '/images/pan_estrella_3.jpg',
    stock_disponible: 25,
    activo: 1,
    costo_produccion_unitario: 1903,
    receta: [
      { id: 9, producto_id: 3, insumo_id: 1, cantidad: 0.08, insumo_nombre: 'Harina de Trigo Especial W300', unidad_medida: 'kg', costo_unitario: 4200, subtotal_costo: 336 },
      { id: 10, producto_id: 3, insumo_id: 4, cantidad: 0.045, insumo_nombre: 'Mantequilla Artesanal 82% MG', unidad_medida: 'kg', costo_unitario: 32000, subtotal_costo: 1440 },
      { id: 11, producto_id: 3, insumo_id: 6, cantidad: 0.015, insumo_nombre: 'Azúcar Blanca Refinada', unidad_medida: 'kg', costo_unitario: 4600, subtotal_costo: 69 },
      { id: 12, producto_id: 3, insumo_id: 2, cantidad: 0.003, insumo_nombre: 'Levadura Fresca Prensada', unidad_medida: 'kg', costo_unitario: 18000, subtotal_costo: 54 },
      { id: 13, producto_id: 3, insumo_id: 5, cantidad: 0.002, insumo_nombre: 'Sal Marina Fina', unidad_medida: 'kg', costo_unitario: 2000, subtotal_costo: 4 },
    ],
  },
  {
    id: 4,
    nombre: 'Ciabatta Rústica de Aceite de Oliva',
    descripcion: 'Pan italiano de alta hidratación con aceite de oliva virgen extra y miga abierta.',
    precio: 4800,
    categoria: 'Pan Blanco',
    imagen_url: '/images/pan_estrella_4.jpg',
    stock_disponible: 22,
    activo: 1,
    costo_produccion_unitario: 2548,
    receta: [
      { id: 14, producto_id: 4, insumo_id: 1, cantidad: 0.35, insumo_nombre: 'Harina de Trigo Especial W300', unidad_medida: 'kg', costo_unitario: 4200, subtotal_costo: 1470 },
      { id: 15, producto_id: 4, insumo_id: 9, cantidad: 0.025, insumo_nombre: 'Aceite de Oliva Virgen Extra', unidad_medida: 'L', costo_unitario: 36000, subtotal_costo: 900 },
      { id: 16, producto_id: 4, insumo_id: 2, cantidad: 0.006, insumo_nombre: 'Levadura Fresca Prensada', unidad_medida: 'kg', costo_unitario: 18000, subtotal_costo: 108 },
      { id: 17, producto_id: 4, insumo_id: 5, cantidad: 0.007, insumo_nombre: 'Sal Marina Fina', unidad_medida: 'kg', costo_unitario: 2000, subtotal_costo: 14 },
      { id: 18, producto_id: 4, insumo_id: 7, cantidad: 0.28, insumo_nombre: 'Agua Purificada Filtrada', unidad_medida: 'L', costo_unitario: 200, subtotal_costo: 56 },
    ],
  },
  {
    id: 5,
    nombre: 'Pan Brioche / Blandito Artesanal',
    descripcion: 'Pan suave y esponjoso dorado al huevo, ideal para sándwich y hamburguesas.',
    precio: 2500,
    categoria: 'Pan Blanco',
    imagen_url: '/images/pan_estrella_5.jpg',
    stock_disponible: 30,
    activo: 1,
    costo_produccion_unitario: 1088,
    receta: [
      { id: 19, producto_id: 5, insumo_id: 1, cantidad: 0.12, insumo_nombre: 'Harina de Trigo Especial W300', unidad_medida: 'kg', costo_unitario: 4200, subtotal_costo: 504 },
      { id: 20, producto_id: 5, insumo_id: 4, cantidad: 0.015, insumo_nombre: 'Mantequilla Artesanal 82% MG', unidad_medida: 'kg', costo_unitario: 32000, subtotal_costo: 480 },
      { id: 21, producto_id: 5, insumo_id: 2, cantidad: 0.003, insumo_nombre: 'Levadura Fresca Prensada', unidad_medida: 'kg', costo_unitario: 18000, subtotal_costo: 54 },
      { id: 22, producto_id: 5, insumo_id: 6, cantidad: 0.010, insumo_nombre: 'Azúcar Blanca Refinada', unidad_medida: 'kg', costo_unitario: 4600, subtotal_costo: 46 },
      { id: 23, producto_id: 5, insumo_id: 5, cantidad: 0.002, insumo_nombre: 'Sal Marina Fina', unidad_medida: 'kg', costo_unitario: 2000, subtotal_costo: 4 },
    ],
  },
  {
    id: 6,
    nombre: 'Pan Especial de la Casa La Estrella',
    descripcion: 'Receta insignia con corteza caramelizada, toque de mantequilla y semillas.',
    precio: 4200,
    categoria: 'Especiales',
    imagen_url: '/images/pan_estrella_6.jpg',
    stock_disponible: 24,
    activo: 1,
    costo_produccion_unitario: 1952,
    receta: [
      { id: 24, producto_id: 6, insumo_id: 1, cantidad: 0.28, insumo_nombre: 'Harina de Trigo Especial W300', unidad_medida: 'kg', costo_unitario: 4200, subtotal_costo: 1176 },
      { id: 25, producto_id: 6, insumo_id: 4, cantidad: 0.020, insumo_nombre: 'Mantequilla Artesanal 82% MG', unidad_medida: 'kg', costo_unitario: 32000, subtotal_costo: 640 },
      { id: 26, producto_id: 6, insumo_id: 2, cantidad: 0.005, insumo_nombre: 'Levadura Fresca Prensada', unidad_medida: 'kg', costo_unitario: 18000, subtotal_costo: 90 },
      { id: 27, producto_id: 6, insumo_id: 5, cantidad: 0.005, insumo_nombre: 'Sal Marina Fina', unidad_medida: 'kg', costo_unitario: 2000, subtotal_costo: 10 },
      { id: 28, producto_id: 6, insumo_id: 7, cantidad: 0.18, insumo_nombre: 'Agua Purificada Filtrada', unidad_medida: 'L', costo_unitario: 200, subtotal_costo: 36 },
    ],
  },
];
